### ISSUE TITLE
菜单栏图标能适配最新macOS吗

### ISSUE THREAD

**Issue by cvpas** [hiiseeu/sharesbar#1]
很棒的项目，盯盘很方便。这个菜单栏图标风格能做到和macOS统一吗？红色有点不搭哈哈哈

**Comment by hiiseeu** [comment]
> 很棒的项目，盯盘很方便。这个菜单栏图标风格能做到和macOS统一吗？红色有点不搭哈哈哈

咳咳，谬赞了，就随手写的，准备重构的，被割韭菜心灰意冷，上班也忙就没搞。那我抽空再捯饬一下吧；

**Comment by hiiseeu** [comment]
> 很棒的项目，盯盘很方便。这个菜单栏图标风格能做到和macOS统一吗？红色有点不搭哈哈哈

v1.0.2版本已修复，更新最新版本试试

**Comment by cvpas** [comment]
release里没有dmg

**Comment by hiiseeu** [comment]
***@***.***D72AE8.7B5F2050]
有呢，可能你那会下的时候没加载出来

发件人: ben-august ***@***.***>
答复: hiiseeu/sharesbar ***@***.***>
日期: 2021年4月1日 星期四 下午3:32
收件人: hiiseeu/sharesbar ***@***.***>
抄送: sun yuxiao ***@***.***>, State change ***@***.***>
主题: Re: [hiiseeu/sharesbar] 菜单栏图标能适配最新macOS吗 (#1)


release里没有dmg
